version: "3.9"

services:
  client:
    container_name: client
    image: next-app
    build: ./client
    ports:
      - 3000:3000
    environment:
      - API_BASE_URL=http://api:3001/
    volumes:
      # - ./client/node_modules:/app/node_modules
      - ./client/components:/app/components
      - ./client/public:/app/public
      - ./client/services:/app/services
      - ./client/src:/app/src
      - ./client/styles:/app/styles

      # depends_on:
      #   - api

      # api:
      #   container_name: api
      #   image: nestjs-app
      #   build: ./api
      #   ports:
      #     - 3001:3001
      #   environment:
      #     - APP_PORT=3001
      #     - DB_TYPE=postgres
      #     - PG_HOST=db
      #     - PG_USER=postgres
      #     - PG_PASSWORD=qwerty
      #     - PG_DB=meuestagio
      #     - PG_PORT=5432
      #   volumes:
      #     - ./api/node_modules:/app/api/node_modules
      #     - ./api/src:/app/api/src
      #     - ./api/dist:/app/api/dist
      #     - ./api/test:/app/api/test
      #     - ./api/.env:/app/api/.env

      #   depends_on:
      # - db
#   db:
#     container_name: db
#     image: postgres
#     ports:
#       - 5432:5432
#     environment:
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=qwerty
#       - POSTGRES_DB=meuestagio
#       - POSTGRES_HOST_AUTH_METHOD=trust
#     volumes:
#       - ./pgdata:/var/lib/postgresql/data

# volumes:
#   pgdata:
#     driver: local
#   bundle_path:
