version: "3.8"

services:
  client:
    container_name: meuestagio_frontend
    build:
      context: ./client
    restart: always
    ports:
      - 3000:3000
    networks:
      - meuestagio_network
    depends_on:
      - api

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: meuestagio_backend
    volumes:
      - ./api:/app
    environment:
      API_PORT: ${API_PORT}
      PG_HOST: ${PG_HOST}
      PG_USER: ${PG_USER}
      PG_PASSWORD: ${PG_PASSWORD}
      PG_DB: ${PG_DB}
      PG_PORT: ${PG_PORT}
      JWT_SECRET: ${JWT_SECRET}
      NODE_ENV: production
      FIREBASE_API_KEY: ${FIREBASE_API_KEY}
      FIREBASE_APP_ID: ${FIREBASE_APP_ID}
      FIREBASE_MESSAGING_SENDER_ID: ${FIREBASE_MESSAGING_SENDER_ID}
    ports:
      - ${API_PORT}:${API_PORT}
    depends_on:
      - db
    networks:
      - meuestagio_network

  db:
    container_name: meuestagio_db
    image: postgres:15
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DB}
    networks:
      - meuestagio_network
    volumes:
      - ./pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    driver: local

networks:
  meuestagio_network:
    external: true
