version: "3.8"

services:
  api:
    build:
      dockerfile: Dockerfile
      context: ./api
      target: development
    command: npm run start:dev
    volumes:
      - ./api:/usr/src/app
      - ./api/node_modules:/usr/src/app/node_modules
      - ./api/dist:/usr/src/app/dist
    environment:
      PORT: 3001
      DB_TYPE: postgres
      PG_HOST: db
      PG_USER: postgres
      PG_PASSWORD: qwerty
      PG_DB: meuestagio
      PG_PORT: 5432
      NODE_ENV: development
      JWT_SECRET: 8noT7pXXsbJcnhwk0qwGwMA4ljnhX5Ts
    ports:
      - 8080:3001
    depends_on:
      - db

  db:
    container_name: db
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_DB=meuestagio
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
    driver: local
  bundle_path:
