version: "3.9"

services:
  # client:
  #   image: next-app
  #   build: ./client
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - ./client/components:/app/components
  #     - ./client/public:/app/public
  #     - ./client/services:/app/services
  #     - ./client/src:/app/src
  #     - ./client/styles:/app/styles
  #   networks:
  #     - app-network

  api:
    container_name: api
    image: nestjs-app
    build: ./api
    ports:
      - 3001:3001
    environment:
      - DB_TYPE=postgres
      - PG_HOST=db
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_DB=postgres
      - PG_PORT=5432
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_DB=meuestagio
    volumes:
      - ./pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    driver: local
  bundle_path:

networks:
  app-network:
    driver: bridge
