import Head from "next/head";
import React from "react";
import { DayPicker } from "react-day-picker";

export default function Home() {
  const [selected, setSelected] = React.useState<Date>();

  let footer = <p>Please pick a day.</p>;
  return (
    <>
      <Head>
        <title>meuestagio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Home Page</h1>
      <DayPicker mode="single" selected={selected} onSelect={setSelected} />
    </>
  );
}
